### ISSUE TITLE
Build and deploy to pypi is failing

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/gwas-sumstats-validator#60]
The build and deploy step of the Gitlab ci/cd is failing and needs to be fixed so that we can make releases https://gitlab.ebi.ac.uk/gwas/gwas-sumstats-validator/-/blob/master/.gitlab-ci.yml

**Comment by jdhayhurst** [comment]
Currently failing on this step, which runs without error locally:
```
$ python -m build
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/builds/gwas/gwas-sumstats-validator/venv/lib/python3.7/site-packages/build/__main__.py", line 214, in <module>
    main(sys.argv[1:], 'python -m build')
  File "/builds/gwas/gwas-sumstats-validator/venv/lib/python3.7/site-packages/build/__main__.py", line 206, in main
    build_package(args.srcdir, outdir, distributions, config_settings, not args.no_isolation, args.skip_dependencies)
  File "/builds/gwas/gwas-sumstats-validator/venv/lib/python3.7/site-packages/build/__main__.py", line 94, in build_package
    _build_in_isolated_env(builder, outdir, distributions, config_settings)
  File "/builds/gwas/gwas-sumstats-validator/venv/lib/python3.7/site-packages/build/__main__.py", line 52, in _build_in_isolated_env
    with IsolatedEnvBuilder() as env:
  File "/builds/gwas/gwas-sumstats-validator/venv/lib/python3.7/site-packages/build/env.py", line 91, in __enter__
    executable, scripts_dir = _create_isolated_env_venv(self._path)
  File "/builds/gwas/gwas-sumstats-validator/venv/lib/python3.7/site-packages/build/env.py", line 203, in _create_isolated_env_venv
    pip_distribution = next(iter(metadata.distributions(name='pip', path=[purelib])))
TypeError: distributions() got an unexpected keyword argument 'name'```

**Comment by jdhayhurst** [comment]
A runaway dependency issue solved by a series commits, finally this one: https://github.com/EBISPOT/gwas-sumstats-validator/commit/d0e0c58a5d9ae0d8a808a0f868396fff3886b88f
