### ISSUE TITLE
TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'

### ISSUE THREAD

**Issue by carbocation** [EBISPOT/gwas-sumstats-validator#72]
I'm not able to successfully run this on macOS because of the following crash:

```
$ ss-validate -f invnorm_max_aa_diam.tsv
(INFO): Validating file extension...
(INFO): ok
(INFO): Validating headers...
(INFO): ok
(INFO): Validating file for squareness...
(INFO): ok
(INFO): Validating rows...
(INFO): ok
(INFO): Validating data...
  0%|                                                                                                                                                    | 0/11622717 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/homebrew/bin/ss-validate", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/validate/validator.py", line 328, in main
    validator.validate_data()
  File "/opt/homebrew/lib/python3.11/site-packages/validate/validator.py", line 113, in validate_data
    for chunk in self.df_iterator():
                 ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/validate/validator.py", line 206, in df_iterator
    df = pd.read_csv(self.file, 
         ^^^^^^^^^^^^^^^^^^^^^^
TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'
```

**Comment by jdhayhurst** [comment]
Hi, this repository has now been deprecated. The validator now resides in https://github.com/EBISPOT/gwas-sumstats-tools - please could you let me know if this still an issue?
